import {defineConfig} from 'powerful-cli';
import config from './exports/powerful.config';

export default defineConfig<CONFIG.Extra>(async (
	{
		returnCheck,
		baseDir,
		packageJson,
		args,
		command,
		utils:{
			extend,
			copyReplace,
			copyCover,
			copyCustom,
			dateFormat,
		},
	},
) => {
	return returnCheck({
		extendConfigs:[
			config,
		],
		envPath:'env',
		extraEnv:{
		},
		extraProp:'v8',
	});
}, async (
	{
		extendConfigs,
		envPath,
		extraEnv,
		returnCheck,
		baseDir,
		packageJson,
		args,
		command,
		utils:{
			extend,
			copyReplace,
			copyCover,
			copyCustom,
			dateFormat,
		},
	},
) => {
	return returnCheck({
		debug:false,
		devServer:{
		},
		emitEntryInjectJs:{
		},
		pages:{
			index:'src/main.ts',
		},
		htmlTemplate:{
			favicon:'template/favicon.ico',
			minify:undefined,
			templateParameters:{
			},
			inject:false,
		},
		publicPath:'auto',
		outputDir:'dist',
		alias:{
		},
		buildFile:{
			emit:command !== 'serve',
			name:command === 'lib'
				? 'lib/build-info.txt'
				: 'build-info.txt',
			content:[
			],
		},
		emitFiles:{
		},
		definePlugin:{
		},
		vConsole:{
			active:false,
			vue:true,
		},
		buildConfig:{
			buildConsole:'normal',
			minimize:'swc',
			sourceMap:true,
			cssSourceMap:false,
			sourceLog:true,
		},
		libConfig:{
			html:{
				template:'template/index.html',
				templateContent:false,
				filename:'index.html',
				title:'',
				favicon:'',
				minify:true,
				templateParameters:undefined,
				inject:undefined,
				publicPath:'lib/',
				base:undefined,
				meta:undefined,
				scriptLoading:'blocking',
			},
			buildConsole:'normal',
			name:packageJson.name,
			entry:'src/lib.ts',
			minimize:'swc',
			sourceMap:false,
			cssSourceMap:false,
			sourceLog:true,
			externals:{
			},
			export:'default',
		},
		copy:{
			dir:'static',
			to:undefined,
			toType:undefined,
			minimize:true,
			filter:undefined,
			transformer:undefined,
		},
		babel:{
			presetOption:{
				browserslistEnv:undefined,
				debug:false,
				useBuiltIns:'usage',
			},
			plugins:[
			],
			polyfills:[
			],
			transpileDependencies:[
			],
			extraEntry:[
			],
		},
		typescript:{
			active:true,
			configFile:undefined,
		},
		eslint:{
			active:true,
			extensions:[
			],
		},
		cacheGroups:{
		},
		report:{
			emit:true,
			type:'html',
			filename:'report',
			statsOptions:null,
		},
		fileManager:command === 'lib'
			? {
				events:{
					onEnd:[
						{
							copy:[
								{
									source:'./dist/assets',
									destination:'./dist/lib/assets',
								},
								{
									source:'./dist/{index.js,index.css}',
									destination:'./dist/lib',
								},
							],
						},
						{
							delete:[
								{
									source:'./dist/{index.js,index.css,assets}',
									options:{
										force:true,
									},
								},
								{
									source:'./lib/',
									options:{
										force:true,
									},
								},
							],
						},
						{
							copy:[
								{
									source:'./dist/lib',
									destination:'./lib',
								},
							],
						},
					],
				},
			}
			: undefined,
		webpackConfig:{
			performance:{
				hints:false,
			},
		},
	});
});